services:
  node-red:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: "bridge"
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - node-red-volume:/data
    environment:
      - TZ=Europe/Vienna
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  node-red-volume:
    external: true
